#
# Copyright © 2023 – 2025 Red Hat, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

- name: Ensure that subordinate group ID ranges are absent
  become: yes
  file:
    path: /etc/subgid
    state: absent

- name: Ensure that subordinate user ID ranges are absent
  become: yes
  file:
    path: /etc/subuid
    state: absent

- name: Install RPM packages
  become: yes
  package:
    name:
      - ShellCheck
      - codespell
      - fish
      - flatpak-session-helper
      - gcc
      - golang
      - golang-github-cpuguy83-md2man
      - meson
      - ninja-build
      - pkgconfig(bash-completion)
      - shadow-utils-subid-devel
      - systemd
      - udisks2
    state: present
    update_cache: "{{ true if zuul.attempts > 1 else false }}"
    use: "{{ 'dnf' if zuul.attempts > 1 else 'auto' }}"

- name: Ensure that 'p11-kit server' is absent
  become: yes
  package:
    name:
      - p11-kit-server
    state: absent
    update_cache: "{{ true if zuul.attempts > 1 else false }}"
    use: "{{ 'dnf' if zuul.attempts > 1 else 'auto' }}"

- name: Ensure that podman(1) is absent
  become: yes
  package:
    name:
      - podman
    state: absent
    update_cache: "{{ true if zuul.attempts > 1 else false }}"
    use: "{{ 'dnf' if zuul.attempts > 1 else 'auto' }}"

- name: Ensure that skopeo(1) is absent
  become: yes
  package:
    name:
      - skopeo
    state: absent
    update_cache: "{{ true if zuul.attempts > 1 else false }}"
    use: "{{ 'dnf' if zuul.attempts > 1 else 'auto' }}"

- name: Download Go modules
  command: go mod download -x
  environment:
    GOINSECURE: go.opencensus.io
  args:
    chdir: '{{ zuul.project.src_dir }}/src'

- name: Initialize Git submodules
  command: git submodule init
  args:
    chdir: '{{ zuul.project.src_dir }}'

- name: Update Git submodules
  command: git submodule update
  args:
    chdir: '{{ zuul.project.src_dir }}'

- name: Check versions of crucial packages
  command: rpm -qa ShellCheck bash-completion codespell *kernel* gcc *glibc* shadow-utils-subid-devel golang golang-github-cpuguy83-md2man flatpak-session-helper
