- name: Install RPM packages from CentOS Stream
  become: yes
  package:
    name:
      - flatpak-session-helper
      - gcc
      - golang
      - httpd-tools
      - meson
      - ninja-build
      - openssl
      - pkgconfig(bash-completion)
      - podman
      - shadow-utils-subid-devel
      - skopeo
      - systemd
      - udisks2

- name: Install RPM packages from CentOS Stream CodeReady Linux Builder
  become: yes
  package:
    enablerepo: crb
    name:
      - golang-github-cpuguy83-md2man

- name: Enable EPEL
  become: yes
  package:
    name:
      - epel-release

- name: Install RPM packages from EPEL
  become: yes
  package:
    name:
      - ShellCheck
      - bats
      - codespell
      - fish

- name: Ensure that 'p11-kit server' is absent
  become: yes
  package:
    name:
      - p11-kit-server
    state: absent

- name: Download Go modules
  command: go mod download -x
  environment:
    GOINSECURE: go.opencensus.io
  args:
    chdir: '{{ zuul.project.src_dir }}/src'

- name: Initialize Git submodules
  command: git submodule init
  args:
    chdir: '{{ zuul.project.src_dir }}'

- name: Update Git submodules
  command: git submodule update
  args:
    chdir: '{{ zuul.project.src_dir }}'

- name: Check versions of crucial packages
  command: rpm -qa ShellCheck bash bash-completion bats codespell *kernel* gcc *glibc* golang golang-github-cpuguy83-md2man shadow-utils-subid-devel podman conmon containernetworking-plugins containers-common container-selinux crun fuse-overlayfs flatpak-session-helper skopeo

- name: Show podman versions
  command: podman version

- name: Show podman debug information
  command: podman info --debug
