---
- hosts: all
  tasks:
    - include_tasks: dependencies.yaml

    - name: Set up build directory
      command: meson setup --fatal-meson-warnings builddir
      args:
        chdir: '{{ zuul.project.src_dir }}'

    - include_tasks: build.yaml
