---
- hosts: all
  tasks:
    - name: Install requirements
      become: yes
      package:
        use: dnf
        name:
          - bash-completion
          - bats
          - flatpak-session-helper
          - golang
          - golang-github-cpuguy83-md2man
          - meson
          - ninja-build
          - podman
          - skopeo
          - systemd
          - udisks2

    - name: Install bats-assert library
      git:
        repo: https://github.com/bats-core/bats-assert
        dest: '{{ zuul.project.src_dir }}/test/system/libs/bats-assert'
        depth: 1
        version: v2.0.0

    - name: Install bats-support library
      git:
        repo: https://github.com/bats-core/bats-support
        dest: '{{ zuul.project.src_dir }}/test/system/libs/bats-support'
        depth: 1
        version: v0.3.0

    - name: Setup environment
      become: yes
      command:
        cmd: systemd-tmpfiles --create
        creates: /run/media

    - name: Check versions of crucial packages
      command: rpm -q golang podman crun conmon fuse-overlayfs flatpak-session-helper

    - name: Show podman versions
      command: podman version

    - name: Show podman debug information
      command: podman info --debug
